all:
	gcc -Wall -Werror -Wextra main.c str_lib.c str_list_lib.c list_lib.c input_lib.c parse_lib.c test_lib.c parse_dic.c hundle_lib.c hundle_num.c -o rush-02

clean:	fclean

fclean:
		rm -f rush-02 
